version: '3.6'

services:
  app:
#    build:
#      context: .
    image: alirezafaghani/surge:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - "REDIS_ADDRESS=redis:6379"
      - "NATS_ADDRESS=nats:4222"
      - "MYSQL_HOST=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PASS=secretpass"
      - "MYSQL_NAME=surge"
      - "MYSQL_PORT=3306"
      - "MIGRATION_DIRECTORY=migration"
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_PORT=8080"
    depends_on:
      - mysql
      - nats
      - redis
    networks:
      - surge

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secretpass"
      - "MYSQL_DATABASE=surge"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - surge

  nats:
    image: nats:latest
    ports:
      - "8222:8222"
    networks:
      - surge

  redis:
    image: redis:latest
    networks:
      - surge

volumes:
  mysql:
networks:
  surge:
    driver: "bridge"